InukChoi/bread-book-backend

src/main/java/com/example/breadbook/Notification/NotificationRepository.java, src/main/java/com/example/breadbook/Notification/model/Notification.java
=> [Feat]Notification add

src/main/java/com/example/breadbook/Notification/NotificationRepository.java, src/main/java/com/example/breadbook/Report/ReportRepository.java, src/main/java/com/example/breadbook/Report/model/Report.java, src/main/java/com/example/breadbook/Report/model/ReportDto.java
report 기본 변수들 넣은 report 파일 푸쉬합니다.
=> [Feat] report add

src/main/java/com/example/breadbook/Report/model/Report.java, src/main/java/com/example/breadbook/domain/book/BookController.java, src/main/java/com/example/breadbook/domain/book/BookRepository.java, src/main/java/com/example/breadbook/domain/book/BookService.java, src/main/java/com/example/breadbook/domain/book/model/Book.java, src/main/java/com/example/breadbook/domain/book/model/BookDto.java, src/main/java/com/example/breadbook/domain/category/CategoryController.java, src/main/java/com/example/breadbook/domain/category/CategoryRepository.java, src/main/java/com/example/breadbook/domain/category/CategoryService.java, src/main/java/com/example/breadbook/domain/category/model/Category.java, src/main/java/com/example/breadbook/domain/product/BookCondition.java, src/main/java/com/example/breadbook/domain/product/ProductController.java, src/main/java/com/example/breadbook/domain/product/ProductRepository.java, src/main/java/com/example/breadbook/domain/product/ProductService.java, src/main/java/com/example/breadbook/domain/product/ProductStatus.java, src/main/java/com/example/breadbook/domain/product/model/Product.java, src/main/java/com/example/breadbook/domain/product/model/ProductDto.java
- Entity, Enum 클래스 완성
**앞으로 해야할 일**
Create, Read 기능을 위하여.. 
- 각 패키지별 필요한 DTO, response 생성,;
- service 작성,;
- controller 작성
=> [Init] product, category, book 패키지 및 하위 클래스 생성

src/main/java/com/example/breadbook/domain/order/OrderRepository.java, src/main/java/com/example/breadbook/domain/order/OrderService.java, src/main/java/com/example/breadbook/domain/order/model/Order.java, src/main/java/com/example/breadbook/domain/order/model/OrderDto.java, src/main/java/com/example/breadbook/domain/order/model/OrderStatus.java
=> [Feat] 주문 관련 기능 추가

src/main/java/com/example/breadbook/domain/review/ReviewRepository.java, src/main/java/com/example/breadbook/domain/review/ReviewService.java, src/main/java/com/example/breadbook/domain/review/model/Review.java, src/main/java/com/example/breadbook/domain/review/model/ReviewDto.java
=> [Feat] 리뷰기능 추가

src/main/java/com/example/breadbook/domain/order/OrderRepository.java, src/main/java/com/example/breadbook/domain/order/OrderService.java, src/main/java/com/example/breadbook/domain/order/model/Order.java, src/main/java/com/example/breadbook/domain/order/model/OrderDto.java, src/main/java/com/example/breadbook/domain/order/model/OrderStatus.java, src/main/java/com/example/breadbook/domain/review/ReviewRepository.java, src/main/java/com/example/breadbook/domain/review/ReviewService.java, src/main/java/com/example/breadbook/domain/review/model/Review.java, src/main/java/com/example/breadbook/domain/review/model/ReviewDto.java, src/main/java/com/example/breadbook/global/response/BaseResponse.java
=> [Feat] BaseResponse추가

src/main/java/com/example/breadbook/domain/member/model/MemberDto.java, src/main/java/com/example/breadbook/domain/notification/NotificationController.java, src/main/java/com/example/breadbook/domain/notification/NotificationRepository.java, src/main/java/com/example/breadbook/domain/notification/NotificationService.java, src/main/java/com/example/breadbook/domain/notification/model/Notification.java, src/main/java/com/example/breadbook/domain/notification/model/NotificationDto.java, src/main/java/com/example/breadbook/domain/report/ReportController.java, src/main/java/com/example/breadbook/domain/report/ReportRepository.java, src/main/java/com/example/breadbook/domain/report/ReportService.java, src/main/java/com/example/breadbook/domain/report/model/Report.java, src/main/java/com/example/breadbook/domain/report/model/ReportDto.java
1. 패키지 첫글자 소문자로 변경
2. domain 패키지 아래로 이동
=> [Rename] rename notification and report

src/main/java/com/example/breadbook/domain/order/OrderController.java, src/main/java/com/example/breadbook/domain/order/OrderService.java, src/main/java/com/example/breadbook/global/response/BaseResponse.java, src/main/java/com/example/breadbook/global/response/BaseResponseMessage.java
=> [Fix] order regist 기능 추가

src/main/java/com/example/breadbook/global/response/BaseResponse.java
=> [Fix] BaseResponse 어노테이션 삭제

src/main/java/com/example/breadbook/domain/order/OrderController.java, src/main/java/com/example/breadbook/domain/order/OrderService.java, src/main/java/com/example/breadbook/domain/order/model/OrderDto.java, src/main/java/com/example/breadbook/domain/review/ReviewRepository.java, src/main/java/com/example/breadbook/global/response/BaseResponse.java, src/main/java/com/example/breadbook/global/response/BaseResponseMessage.java
=> [Fix] orderDetails 추가

src/main/java/com/example/breadbook/domain/order/OrderRepository.java, src/main/java/com/example/breadbook/domain/order/OrderService.java, src/main/java/com/example/breadbook/domain/order/model/OrderDto.java, src/main/java/com/example/breadbook/domain/report/ReportController.java, src/main/java/com/example/breadbook/domain/review/ReviewRepository.java, src/main/java/com/example/breadbook/domain/review/ReviewService.java
=> [Fix] OrderService {findByMember} 매개변수 수정

src/main/java/com/example/breadbook/domain/review/ReviewController.java, src/main/java/com/example/breadbook/domain/review/ReviewService.java, src/main/java/com/example/breadbook/global/response/BaseResponseMessage.java
=> [Feat] ReviewController 추가

src/main/java/com/example/breadbook/domain/review/ReviewController.java, src/main/java/com/example/breadbook/domain/review/ReviewService.java, src/main/java/com/example/breadbook/global/response/BaseResponseMessage.java
=> [Fix] Review 확인 기능 추가

src/main/java/com/example/breadbook/domain/chat/ChattingRoomController.java, src/main/java/com/example/breadbook/domain/chat/ChattingRoomRepository.java, src/main/java/com/example/breadbook/domain/chat/ChattingRoomService.java, src/main/java/com/example/breadbook/domain/chat/model/ChattingRoom.java, src/main/java/com/example/breadbook/domain/chat/model/ChattingRoomDto.java, src/main/java/com/example/breadbook/domain/chat/model/Message.java
=> Feat: 채팅방 엔티티 추가 #45

src/main/java/com/example/breadbook/domain/chat/ChattingRoomService.java, src/main/java/com/example/breadbook/domain/chat/MessageRepository.java, src/main/java/com/example/breadbook/domain/chat/ParticipantRepository.java, src/main/java/com/example/breadbook/domain/chat/model/Participant.java
=> [Feat] ChattingRoomService 추가

build.gradle, src/main/java/com/example/breadbook/domain/member/CustomOAuth2UserService.java, src/main/java/com/example/breadbook/domain/member/MemberController.java, src/main/java/com/example/breadbook/domain/member/MemberRepository.java, src/main/java/com/example/breadbook/domain/member/MemberService.java, src/main/java/com/example/breadbook/domain/member/model/CustomOAuth2Member.java, src/main/java/com/example/breadbook/domain/member/model/Member.java, src/main/java/com/example/breadbook/domain/member/model/MemberDto.java, src/main/java/com/example/breadbook/global/config/SecurityConfig.java, src/main/java/com/example/breadbook/global/config/filter/LoginFilter.java, src/main/java/com/example/breadbook/global/handler/OAuth2SuccessHandler.java, src/main/java/com/example/breadbook/global/utils/JwtUtil.java, src/main/resources/application.yml
소셜 로그인 구현 및 기타 수정
- 카카오, 네이버, 구글 로그인 구현
- Jwt 토큰 속성 수정(젠더, 생년월일, 점수 제거 / 제공자 추가)
- 멤버 엔티티 수정(제공자 추가 / 기본이미지 url 수정)
=> [Feat] 소셜 로그인 구현 #19 #20 #21

src/main/java/com/example/breadbook/domain/test/TestController.java, src/main/java/com/example/breadbook/domain/test/TestService.java, src/main/java/com/example/breadbook/domain/test/model/TestDto.java, src/main/java/com/example/breadbook/global/config/SecurityConfig.java
=> [Feat] main화면 유저 정보 불러오기

src/main/java/com/example/breadbook/domain/order/OrderController.java
=> [Fix] OrderController 수정

src/main/java/com/example/breadbook/domain/notification/model/NotificationDto.java, src/main/java/com/example/breadbook/domain/order/OrderController.java, src/main/java/com/example/breadbook/domain/order/OrderService.java, src/main/java/com/example/breadbook/domain/order/model/OrderDto.java, src/main/java/com/example/breadbook/domain/review/ReviewService.java
=> [Fix] product memberIdx 수정 관련 order 수정

src/main/java/com/example/breadbook/domain/book/BookController.java, src/main/java/com/example/breadbook/domain/book/BookRepository.java, src/main/java/com/example/breadbook/domain/book/BookService.java, src/main/java/com/example/breadbook/domain/book/model/BookDto.java
- **향후 book 을 등록하고 난 뒤 product에 저장할 때 잘 연결되는지 확인해야함**!!!!🌟⭐🌟
=> [Feat] 책을 검색하고 등록하는 기능 Book

src/main/java/com/example/breadbook/domain/chat/ChattingWebSocketController.java, src/main/resources/application.yml
application.yml에서 uploadpath 부분 주석처리 풀었는데 돌렸을 때 안되면 환경 변수에 한 번 추가해주셔요~
=> [Feat] 실시간 채팅 기능 구현

src/main/java/com/example/breadbook/domain/member/model/Member.java, src/main/java/com/example/breadbook/domain/member/repository/MemberRepository.java, src/main/java/com/example/breadbook/domain/order/OrderController.java, src/main/java/com/example/breadbook/domain/order/OrderRepository.java, src/main/java/com/example/breadbook/domain/order/OrderService.java, src/main/java/com/example/breadbook/domain/order/model/Order.java, src/main/java/com/example/breadbook/domain/order/model/OrderDto.java, src/main/java/com/example/breadbook/domain/product/model/Product.java, src/main/java/com/example/breadbook/domain/review/model/Review.java
=> [Fix] orderList N+1문제 해결
